feat: add main service
mkudryavtsev90/java-explore-with-me pull request #2
Opened 2023-02-15 20:00 UTC by mkudryavtsev90

Добавлена основная функциональность EWM Main сервиса

2023-02-16 06:49 UTC, Frilock requested changes
Доброе утро, оставил ряд комментариев к работе. Жду новую версию.

2023-02-16 06:49 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/controller/publicApi/CategoryPublicRestControllerV1.java
> +public class CategoryPublicRestControllerV1 {
А чего вдруг вы решили добавлять окончание с версией в свои контроллеры? В спецификации я такого не помню, или что то изменилось? Мне лично не очень нравится такая тема

2023-02-16 06:49 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/dto/event/UpdateEventAdminRequest.java
> +    String annotation;
А чего тут модификаторы не проставили? Везде писали, а тут нет, давайте сделаем идентично

2023-02-16 06:49 UTC, Frilock commented on main-service/src/main/resources/schema.sql
> +    name  VARCHAR(255)                            NOT NULL,
Размерность полей смущает, для имени нужно столько выделять?

2023-02-16 06:49 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/repository/CategoryRepository.java
> +@Repository
Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2023-02-16 06:49 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/repository/ParticipationRequestRepository.java
> +    @Query("select req " +
А тут query обязателен? По моему нормально в теле метода укладываетесь

2023-02-16 06:49 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/service/impl/CompilationServiceImpl.java
> +        if (Objects.isNull(pinned)) {
Можно конструкцию на тернарное выражение заменить, будет компактнее

2023-02-16 06:49 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/service/impl/EventServiceImpl.java
> +        if (event.getState().equals(EventState.PUBLISHED)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2023-02-16 06:49 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/service/impl/CategoryServiceImpl.java
> +        //TODO
Меня это TODO смущает, либо уберите комментарий либо выполните доработку которую хотели

2023-02-16 06:49 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/service/impl/CategoryServiceImpl.java
> +            throw new NotFoundException("Category with id " + id + " not found");
Category with id " + id + " not found" повторяется более трех раз - вынесите в константу

2023-02-16 08:27 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/controller/publicApi/CategoryPublicRestControllerV1.java
> +public class CategoryPublicRestControllerV1 {
Да это я начитался про версионирование контроллеров и думал что это best practice:) убрал

2023-02-16 08:33 UTC, mkudryavtsev90 commented on main-service/src/main/resources/schema.sql
> +    name  VARCHAR(255)                            NOT NULL,
Сделал 100

2023-02-16 08:33 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/repository/CategoryRepository.java
> +@Repository
Убрал

2023-02-16 08:38 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/repository/ParticipationRequestRepository.java
> +    @Query("select req " +
Да, смутила двойная вложенность Event_Initiator_Id, подумал что через Query точно заработает. Переделал через имя метода

2023-02-16 08:45 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/service/impl/CompilationServiceImpl.java
> +        if (Objects.isNull(pinned)) {
Готово

2023-02-16 08:59 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/service/impl/EventServiceImpl.java
> +        if (event.getState().equals(EventState.PUBLISHED)) {
Переделал

2023-02-16 09:48 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/service/impl/CategoryServiceImpl.java
> +            throw new NotFoundException("Category with id " + id + " not found");
Готово

2023-02-16 10:44 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/service/impl/CategoryServiceImpl.java
> +        //TODO
Готово

2023-02-16 10:45 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/dto/event/UpdateEventAdminRequest.java
> +    String annotation;
Действительно, торопился просто) Добавил модификаторы

2023-02-17 05:30 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/controller/publicApi/CategoryPublicRestControllerV1.java
> +public class CategoryPublicRestControllerV1 {
Честно говоря не видел на проектах такого, да и вообще потом это версионирование захламляет код и ОЧЕНЬ усложняет поддержку, как раз на текущем проекте похожая проблема

2023-02-17 05:31 UTC, Frilock approved these changes
Доброе утро. Принято

2023-02-17 05:43 UTC, merged