feat: add comments feature
mkudryavtsev90/java-explore-with-me pull request #3
Opened 2023-02-18 07:32 UTC by mkudryavtsev90

2023-02-18 08:45 UTC, Frilock requested changes
Добрый день, в целом все здорово, я написал ряд комментариев, но возможно это детали задачи. Посмотрите, если что просто на них мне ответьте

2023-02-18 08:45 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/controller/adminApi/CommentAdminRestController.java
> +    public void deleteById(@PathVariable Long commentId) {
А разве админ не может обновить комментарий?

2023-02-18 08:45 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/dto/comment/CommentDto.java
> +    private LocalDateTime created;
Мне кажется что нужна еще дата обновления (последнего обновления) комментария. Вроде метод patch у Вас есть

2023-02-18 08:45 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/dto/comment/CommentRequestDto.java
> +public class CommentRequestDto {
А идентификатор комментария не нужен Вам? Просто если будет 2 одинаковых объекта с текстом, то что будет?

2023-02-18 08:45 UTC, Frilock commented on main-service/src/main/java/ru/practicum/mainservice/service/impl/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
Я бы Вам предложил еще тесты на свой сервис реализовать, а то тесты постмана это одно, но unit тесты тоже хорошая практика.

2023-02-19 08:42 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/controller/adminApi/CommentAdminRestController.java
> +    public void deleteById(@PathVariable Long commentId) {
Теперь может)

2023-02-19 09:08 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/dto/comment/CommentDto.java
> +    private LocalDateTime created;
Готово

2023-02-19 09:09 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/dto/comment/CommentRequestDto.java
> +public class CommentRequestDto {
Разделил на 2 dto: NewCommentDto и UpdateCommentDto. В первом случае id не нужен, а во второй добавил поле id

2023-02-19 21:38 UTC, mkudryavtsev90 commented on main-service/src/main/java/ru/practicum/mainservice/service/impl/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
Готово

2023-02-20 05:49 UTC, Frilock approved these changes
Принято, здорово

2023-02-20 07:48 UTC, merged